CREATE TABLE FABRICANTE (
  idfab INTEGER UNSIGNED  NOT NULL  ,
  nomfab VARCHAR(50)  NULL  ,
  direccion VARCHAR(100)  NULL    ,
PRIMARY KEY(idfab));



CREATE TABLE OFICINA (
  oficina INTEGER UNSIGNED  NOT NULL  ,
  ciudad VARCHAR(100)  NULL  ,
  region VARCHAR(100)  NULL  ,
  dir INTEGER UNSIGNED  NULL  ,
  objetivo FLOAT  NULL  ,
  ventas FLOAT  NULL    ,
PRIMARY KEY(oficina));



CREATE TABLE CLIENTE (
  numclie INTEGER UNSIGNED  NOT NULL  ,
  rep VARCHAR(100)  NOT NULL  ,
  nombre VARCHAR(100)  NULL  ,
  limitecredito FLOAT  NULL    ,
PRIMARY KEY(numclie, rep));



CREATE TABLE PRODUCTO (
  idproducto INTEGER UNSIGNED  NOT NULL  ,
  FABRICANTE_idfab INTEGER UNSIGNED  NOT NULL  ,
  descripcion TEXT  NULL  ,
  precio FLOAT  NULL  ,
  existencias INTEGER UNSIGNED  NULL    ,
PRIMARY KEY(idproducto)  ,
INDEX PRODUCTO_FKIndex1(FABRICANTE_idfab),
  FOREIGN KEY(FABRICANTE_idfab)
    REFERENCES FABRICANTE(idfab)
      ON DELETE RESTRICT
      ON UPDATE CASCADE);



CREATE TABLE EMPLEADO (
  numemp INTEGER UNSIGNED  NOT NULL  ,
  OFICINA_oficina INTEGER UNSIGNED  NOT NULL  ,
  nombre VARCHAR(50)  NULL  ,
  edad INTEGER UNSIGNED  NULL  ,
  titulo VARCHAR(100)  NULL  ,
  fechacontratado DATE  NULL  ,
  jefe VARCHAR(100)  NULL  ,
  cuota FLOAT  NULL  ,
  ventas FLOAT  NULL    ,
PRIMARY KEY(numemp)  ,
INDEX EMPLEADO_FKIndex1(OFICINA_oficina),
  FOREIGN KEY(OFICINA_oficina)
    REFERENCES OFICINA(oficina)
      ON DELETE RESTRICT
      ON UPDATE CASCADE);



CREATE TABLE PEDIDO (
  numpedido INTEGER UNSIGNED  NOT NULL  ,
  FABRICANTE_idfab INTEGER UNSIGNED  NOT NULL  ,
  PRODUCTO_idproducto INTEGER UNSIGNED  NOT NULL  ,
  CLIENTE_rep VARCHAR(100)  NOT NULL  ,
  CLIENTE_numclie INTEGER UNSIGNED  NOT NULL  ,
  EMPLEADO_numemp INTEGER UNSIGNED  NOT NULL  ,
  fechapedido DATE  NULL  ,
  cantidad INTEGER UNSIGNED  NULL  ,
  importe INTEGER UNSIGNED  NULL    ,
PRIMARY KEY(numpedido)  ,
INDEX PEDIDO_FKIndex1(EMPLEADO_numemp)  ,
INDEX PEDIDO_FKIndex2(CLIENTE_numclie, CLIENTE_rep)  ,
INDEX PEDIDO_FKIndex3(PRODUCTO_idproducto)  ,
INDEX PEDIDO_FKIndex4(FABRICANTE_idfab),
  FOREIGN KEY(EMPLEADO_numemp)
    REFERENCES EMPLEADO(numemp)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(CLIENTE_numclie, CLIENTE_rep)
    REFERENCES CLIENTE(numclie, rep)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(PRODUCTO_idproducto)
    REFERENCES PRODUCTO(idproducto)
      ON DELETE RESTRICT
      ON UPDATE CASCADE,
  FOREIGN KEY(FABRICANTE_idfab)
    REFERENCES FABRICANTE(idfab)
      ON DELETE RESTRICT
      ON UPDATE CASCADE);




